* Architecture

** Variables

Public variables.

#+begin_src elisp
  (defvar git-review-change-id nil "The unique id of a change.")
  (defvar git-review-patchset nil "The patchset of the current change.")
  (defvar git-review-project nil "The name of the current project.")
  (defvar git-review-add-remote-conversations nil "Function that returns remote conversations.")
#+end_src

Private variables.

#+begin_src elisp
  (defvar git-review--changes nil "All changes.")
  (defvar git-review--change nil "The current change.")
  (defvar git-review--patchset nil "The current patchset.")
  (defvar git-review--rebased-files nil "List of files that are rebased.")
  (defvar git-review--unchanged-files nil "List of files that are unchanged.")
  (defvar git-review--conversations nil "List of conversations.")
#+end_src

** Data structures

*** Changes

=git-review--changes= is a list of property lists.

#+begin_src elisp
  '((:id "change-id1"
         :conversations (list)
         :patchsets (list)
         :project "project-name"
         :review-metadata (list)
         :current-patchset 2)
    (:id "change-id2"
         ...))
#+end_src

*** Patchset

A patchset is a property list.

#+begin_src elisp
  '(:commit-hash "sha1"
                 :parent-hash "sha1"
                 :current-file "file1.cpp"
                 :previous-file "file2.cpp"
                 :base-patchset 1
                 :files (list))
#+end_src

*** Conversations

A conversation is a property list.

#+begin_src elisp
  '(:id "identifier"
        :comments (list)
        :resolved t
        :location '((start-line . 5)
                    (end-line . 6)
                    (start-column . 10)
                    (end-column . 20))
        :commentable t)
#+end_src

*** Comments

A comment is a property list.

#+begin_src elisp
  '(:id "identifier"
        :user "John Doe"
        :message "Hello"
        :remote t
        :side a
        :published t)
#+end_src

*** File

A file is a property list.

#+begin_src elisp
  '(:filename "foo.cpp"
              :original-filename "bar.cpp"
              :type "MODIFIED"
              :metadata '((autogenerated . t)))
#+end_src

*** Review Metadata

A metadata is a property list.

#+begin_src elisp
  '(:id "ps1"
        :reviewed-files ("foo.cpp")
        :rebased-files ("bar.cpp")
        :unchanged-files ("baz.cpp"))
#+end_src

** Implementation details

Updating an existing change with =pushnew= doesn't work.

#+begin_src elisp
  (let ((changes '((:id 1 :name "niklas")
                   (:id 2 :name "tira"))))
    (cl-pushnew '(:id 1 :name "katarina")
                changes
                :test (lambda (a b) (equal (plist-get a :id) (plist-get b :id))))
    changes)
#+end_src

#+RESULTS:
| :id | 1 | :name | niklas |
| :id | 2 | :name | tira   |

Updating an existing change with =push= and =seq-remove=.

#+begin_src elisp
  (let ((changes '((:id 1 :name "niklas")
                   (:id 2 :name "tira")))
        (change '(:id 1 :name "katarina")))
    ;; Delete existing change
    (setq changes
          (seq-remove (lambda (it)
                        (equal (plist-get it :id)
                               (plist-get change :id)))
                      changes))
    ;; Add updated change
    (push change changes)
    changes)

#+end_src

#+RESULTS:
| :id | 1 | :name | katarina |
| :id | 2 | :name | tira     |

** Workflows

- Opening patchset3 of a change. The review should contain remote comments if there are any. The user should be able to switch the base patchset which by default is nil and replace it with patchset2. This should alter which files are being list. It should also update the progress given that the number of interesting files could have changed. If the current file is still of interest it should be kept as the currently viewed file, otherwise it should switch to commit message. When the base change it will alter which comments that gets displayed. It will also alter the files that are being tagged as unchanged or rebased.

